create table if not exists investimento.composicao_capital_cvm (
    id bigint generated by default as identity primary key,

    codigo_cvm text not null,

    cnpj text,

    data_referencia date not null,

    versao integer,

    documento text not null,

    qt_acao_ordin_cap_integr bigint,

    qt_acao_pref_cap_integr bigint,

    qt_acao_total_cap_integr bigint,

    qt_acao_ordin_tesouro bigint,

    qt_acao_pref_tesouro bigint,

    qt_acao_total_tesouro bigint,

    qt_acao_ordin_circulacao bigint,

    qt_acao_pref_circulacao bigint,

    qt_acao_total_circulacao bigint,

    fonte text not null,

    coletado_em timestamptz not null
        default now(),

    constraint composicao_capital_cvm_documento_check
        check (
            documento in (
                'DFP',
                'ITR'
            )
        ),

    constraint composicao_capital_cvm_codigo_data_doc_key
        unique (
            codigo_cvm,
            data_referencia,
            documento
        )
);


create index if not exists
    idx_composicao_capital_cvm_codigo_data

    on investimento.composicao_capital_cvm (
        codigo_cvm,
        data_referencia desc
    );


create index if not exists
    idx_composicao_capital_cvm_cnpj_data

    on investimento.composicao_capital_cvm (
        cnpj,
        data_referencia desc
    );
